# Option 2: Complete local setup with PostgreSQL and data ingestion
version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: credit_approval_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  web:
    build: .
    entrypoint: ["/usr/local/bin/docker-entrypoint-with-data.sh"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=1
      - PGHOST=db
      - PGDATABASE=credit_approval_db
      - PGUSER=postgres
      - PGPASSWORD=password
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=admin123
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
    restart: unless-stopped

  celery:
    build: .
    command: celery -A Alemeno_RESt_API worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=1
      - PGHOST=db
      - PGDATABASE=credit_approval_db
      - PGUSER=postgres
      - PGPASSWORD=password
    restart: unless-stopped

volumes:
  postgres_data: